language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover
  - phpunit -c phpunit.xml.dist --coverage-text

notifications:
    email: false

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer update --dev
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover