services:
    zen.event.dispatcher:
        class: %zen.event.dispatcher.class%
        arguments:
            event.dispatcher: @event_dispatcher

    zen_manager:
        class: %zen.manager.class%
        arguments:
            mailer.adapter: @=service(parameter('zen_mailer_adapter'))
            send.email.event.dispatcher: @zen.event.dispatcher